### ISSUE TITLE
UI Perfomance

### ISSUE THREAD

**Issue by sampaioxsamuel** [cyberwizard1001/ryzen-opencore#1]

**Comment by cyberwizard1001** [comment]
Hey! The graphics are slower than you'd see with the same setup on Windows, yes.. noticeably so. Even Indie games become sluggish. However, the graphics drivers are bundled with the OS and there seems to be no way to get a CUDA / GeForce Game Ready driver that supports our setup. However, regular OS graphics, video playback, screensharing and recording all work as expected.

**Comment by cyberwizard1001** [comment]
That said, please make sure nv_disable=1 is not one of your boot parameters.
